# https://neptune.ai

neptune:
  _target_: pytorch_lightning.loggers.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  # Neptune project placeholder
  project: PLACEHOLDER
  prefix: ""
