# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  # Path to use for tensorboard logs
  save_dir: "PLACEHOLDER"
  name: "default"
  version: "${model_name}"
  log_graph: False
  default_hp_metric: False
  prefix: ""
